"""add password hash

Revision ID: 17e032994322
Revises: 38ecb03dc5c1
Create Date: 2025-10-16 00:02:55.312981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17e032994322'
down_revision: Union[str, Sequence[str], None] = '38ecb03dc5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Update existing records with a default value (you might want to change this)
    op.execute("UPDATE users SET password_hash = 'temp_hash_needs_reset' WHERE password_hash IS NULL")
    
    # Now alter the column to be NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
